config/routes.rb
PopUpArchive::Application.routes.draw do

  use_doorkeeper do
    controllers :applications => 'oauth/applications'
  end

  root to: "directory/dashboard#guest"

  # canonical hostname+protocol in production
  if Rails.env.production?
    # check protocol
    constraints(:protocol => 'http://') do
      match "/(*path)" => redirect { |params, req|
        query_params = req.params.except(:path, :format, :protocol)
        "#{ENV['SERVER_HOSTNAME']}/#{params[:path]}#{query_params.keys.any? ? "?" + query_params.to_query : ""}"
      },  via: [:get, :post, :head]
    end
  end

  #devise_for ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: 'users/registrations', invitations: 'users/invitations', omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :task_list
    resources :soundcloud_callback
    get 'total_usage', to: 'accounts#total_usage'
    resources :accounts
  end

  get 'su' => 'switch_user#set_current_user'

  get 'media/:token/:expires/:use/:class/:id/:name.:extension', controller: 'media', action: 'show', constraints: {name: /[^\/]+/}
  get 'media/:class/:idhex/:name.:extension', controller: 'media', action: 'permanent', constraints: {name: /[^\/]+/}

  get 'embed_player/:name/:file_id/:item_id/:collection_id', controller: 'embed_player', action: 'show', constraints: {name: /[^\/]+/}

  get 'tplayer/:file_id',        controller: 'embed_player', action: 'tplayer'
  get 'tplayer/:file_id/:title', controller: 'embed_player', action: 'tplayer'
  get 'player/:file_id/',        controller: 'embed_player', action: 'iframe'

  get 'oembed', controller: 'oembed', action: 'show'

  get 'test/show', controller: 'test', action: 'show'

  post 'callback/test',      controller: 'callbacks', action: 'tester'
  post '/invite', controller: 'application', action: 'invite'
  post 'fixer_callback/:id', controller: 'callbacks', action: 'fixer', as: 'audio_file_fixer_callback', model_name: 'audio_file'

  post 'fixer_callback/files/:model_name/:id', controller: 'callbacks', action: 'fixer', as: 'fixer_callback'

  post 'amara_callback', controller: 'callbacks', action: 'amara', as: 'amara_callback'

  post 'speechmatics_callback/files/:model_name/:model_id', controller: 'callbacks', action: 'speechmatics', as: 'speechmatics_callback'
  post 'voicebase_callback/files/:model_name/:model_id', controller: 'callbacks', action: 'voicebase', as: 'voicebase_callback'

  post 'stripe_webhook', controller: 'callbacks', action: 'stripe_webhook', as: 'stripe_webhook'

  get 'sitemap.xml', :to => 'sitemap#sitemap', as: 'sitemap', defaults: { format: 'xml' }

  post 'headcheck', :to => 'api/v1/audio_files#head_check'

  get 'organization/:org_id/member/:invitation_token', controller: 'organization', action: 'confirm_invite'

  # sharing shortcut
  get 't/:item_id',               controller: 'item', action: 'short'
  get 't/:item_id/:start',        controller: 'item', action: 'short'
  get 't/:item_id/:start/:end',   controller: 'item', action: 'short'

  namespace :api, defaults: { format: 'json' }, path: 'api' do
    scope module: :v1, constraints: ApiVersionConstraint.new(version: 1, default: true) do
      root to: 'status#info'

      get '/stats' => 'status#stats'

      get '/me' => 'users#me'
      put '/me/credit_card' => 'credit_cards#update'
      put '/me/subscription' => 'subscriptions#update'
      get '/users/me' => 'users#me'
      put '/users/me/credit_card' => 'credit_cards#update'
      put '/users/me/subscription' => 'subscriptions#update'

      get '/usage'        => 'users#usage'
      get '/usage/:limit' => 'users#usage'
      get '/users/usage'  => 'users#usage'
      get '/users/usage/:limit' => 'users#usage'

      post '/credit_card' => 'credit_cards#save_token'

      get '/test/croak' => 'test#croak'
      resources :test

      resource :last_items
      resource :search
      resources :items, only: [] do
        resources :audio_files do
          post '',                     action: 'update'
          get  'transcript_text',      action: 'transcript_text'
          get  'upload_to',            action: 'upload_to'
          post 'order_transcript',     action: 'order_transcript'
          post 'add_to_amara',         action: 'add_to_amara'
          post 'listens',              action: 'listens'
          get  'transcript/premium/cost',  action: 'premium_transcript_cost'
          post 'transcript/premium/order', action: 'order_premium_transcript'

          # s3 upload actions
          get  'chunk_loaded',         action: 'chunk_loaded'
          get  'get_init_signature',   action: 'init_signature'
          get  'get_chunk_signature',  action: 'chunk_signature'
          get  'get_end_signature',    action: 'end_signature'
          get  'get_list_signature',   action: 'list_signature'
          get  'get_delete_signature', action: 'delete_signature'
          get  'get_all_signatures',   action: 'all_signatures'
          get  'upload_finished',      action: 'upload_finished'

          resource :transcript
        end
        resources :image_files do
          get  'upload_to',            action: 'upload_to'

          # s3 upload actions
          get  'chunk_loaded',         action: 'chunk_loaded'
          get  'get_init_signature',   action: 'init_signature'
          get  'get_chunk_signature',  action: 'chunk_signature'
          get  'get_end_signature',    action: 'end_signature'
          get  'get_list_signature',   action: 'list_signature'
          get  'get_delete_signature', action: 'delete_signature'
          get  'get_all_signatures',   action: 'all_signatures'
          get  'upload_finished',      action: 'upload_finished'
        end
        resources :entities
        resources :contributions
      end

      resources :transcripts

      resources :timed_texts

      resources :speakers

      resources :organizations
      post '/organizations/:id/member' => 'organizations#member'
      put '/organizations/:id/member' => 'organizations#delete_member'

      resources :plans

      resources :collections do
        collection do
          resources :public_collections, path: 'public', only: [:index]
        end
        resources :items
        resources :people
        resources :image_files do
          get  'upload_to',            action: 'upload_to'

          # s3 upload actions
          get  'chunk_loaded',         action: 'chunk_loaded'
          get  'get_init_signature',   action: 'init_signature'
          get  'get_chunk_signature',  action: 'chunk_signature'
          get  'get_end_signature',    action: 'end_signature'
          get  'get_list_signature',   action: 'list_signature'
          get  'get_delete_signature', action: 'delete_signature'
          get  'get_all_signatures',   action: 'all_signatures'
          get  'upload_finished',      action: 'upload_finished'
        end
      end
      resources :csv_imports
    end
  end

  # used only for dev and test
  mount JasmineRails::Engine => "/jasmine" if defined?(JasmineRails)

  authenticate :user, lambda { |u| u.super_admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  match '/api/*path', to: 'api/base#not_found', via: [:get, :post]
  match '*path', to: 'directory/dashboard#user', via: [:get, :post]
  match '*path', to: 'directory/dashboard#guest', constraints: GuestConstraint.new(true), via: [:get, :post]
  match '*path', to: 'directory/dashboard#user', constraints: GuestConstraint.new(false), via: [:get, :post]
end

app/controllers/embed_player_controller.rb
class EmbedPlayerController < ApplicationController
  def show
    @name=params[:name]
    @file_id=params[:file_id]
    @item_id=params[:item_id]
    @collection_id=params[:collection_id]
    @mp3 = AudioFile.find(params[:file_id]).public_url(extension: :mp3)
    @ogg = AudioFile.find(params[:file_id]).public_url(extension: :ogg)
  end

  # embedable player with transcript
  def tplayer
    @embed      = params[:embed] ? true : false
    @file_id    = params[:file_id]
    @audio_file = AudioFile.find(@file_id)
    may_read    = true
    if !@audio_file.item.is_public
      logger.warn("private item");
      if current_user
        ability = Ability.new(current_user)
        if !ability.can?(:read, @audio_file.item)
          logger.warn("current_user may not read")
          may_read = false
        end
      else
        logger.warn("no current_user")
        may_read = false
      end
    end
    if !may_read
      respond_to do |format|
        format.html {
          render :formats => [:html], :file => File.join(Rails.root, 'public', '403'), :status => 403
        }
        format.json {
          render :text => { :error => "permission denied", :status => 403 }.to_json, :status => 403
        }
      end
      return
    end
    @mp3        = @audio_file.url(:mp3)
    @ogg        = @audio_file.url(:ogg)
    @transcript = @audio_file.best_transcript
    @title      = params[:title] || @audio_file.item.title
    @chunk_size = params[:chunk] || 30
    @start      = params[:start] || 0
    @end        = params[:end]   || false

    respond_to do |format|
      format.html {
        render :formats => [:html]
      }
      format.json {
        render :json => {
          file_id: @file_id,
          mp3:     @mp3,
          ogg:     @ogg,
          title:   @title,
          start:   @start,
          end:     @end
        }.to_json, :callback => params[:callback]
      }
    end
  end

  def iframe
    @file_id    = params[:file_id]
  end

end

app/views/embed_player/_tplayer_player.html.erb
<table id="pua-tplayer-<%= @file_id %>-player" class="pua-tplayer">
 <tr class="img-player">
  <td class="img">
   <a href="/collections/<%= @audio_file.item.collection_id %>/items/<%= @audio_file.item_id %>/" target="_blank">
     <img src="<%= @audio_file.item.image_url || asset_path('minimark.png') %>" />
   </a>
  </td>
  <td class="tplayer"> 
   <div id="pua-tplayer-<%= @file_id %>" class="jp-jplayer pua-tplayer"></div>
   <div id="jp_container-<%= @file_id %>" class="jp-audio player">
     <div class="jp-type-single">
       <div class="jp-gui jp-interface">
         <div class="jp-title">
           <h2><%= @title %></h2>
         </div>
         <table class="tplayer-bar">
          <tr>
          <td class="jp-controls">
           <button id="jp-reverse-button-<%= @file_id %>" class="jp-rewind player-button">
               <i class="fa fa-fast-backward"></i>
           </button>
           <button id="jp-play-button-<%= @file_id %>" class="jp-play player-button">
               <i class="fa fa-play"></i>
           </button>
           <button id="jp-pause-button-<%= @file_id %>" class="jp-pause player-button">
               <i class="fa fa-pause"></i>
           </button>
          </td>
          <td class="jp-progress">
           <div class="calculating"><i class="fa fa-cog fa-spin"></i> Calculating</div>
           <div class="jp-seek-bar">
             <div class="jp-play-bar"></div>
           </div>
          </td>
          <td class="tplayer-stats">
 
           <div class="jp-time-holder">
             <div class="jp-current-time" role="timer" aria-label="time"></div> / 
             <div class="jp-duration" role="timer" aria-label="duration"></div>
           </div>
 
           <div class="pua-links">
             <a class="jp-popuplink pua-up-link" href="/collections/<%= @audio_file.item.collection_id %>/items/<%= @audio_file.item_id %>/" target="_blank"><span title="up"></span></a>
           </div>

          <!-- scrubber used for drawing waveform, not displayed -->
           <div class="scrubber"><canvas></canvas></div>
          </td>

         </tr>
         </table>
       </div>

       <div class="jp-no-solution">
         <span>Update Required</span>
         To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
       </div>
     </div>
   </div>
  </td>
 </tr>
</table>

app/views/embed_player/_tplayer_player_full.html.slim
- logos = { "soundcloud" => ENV['SOUNDCLOUD_LOGO_SMALL']}
- file_id    ||= @file_id
- audio_file ||= @audio_file || AudioFile.find(file_id.to_i)
- title      ||= @title
- item       ||= @item || @audio_file.item

.pua-tplayer id="pua-tplayer-#{file_id}-player"
    .img-player
      .jp-jplayer.pua-tplayer id="pua-tplayer-#{file_id}"
      .jp-audio.player id="jp_container-#{file_id}" 
        .jp-type-single
          -if audio_file.item.image_thumb
            .img
              a href="#{audio_file.item.digital_location}" target="_blank" 
                img src="#{audio_file.item.image_thumb}"
          .body.jp-gui.jp-interface
            .jp-title
              h2 #{item.title}
            .title-sub
              p
                - if item.respond_to?(:coll_categories)
                  - item.coll_categories.each do |category|
                    a.category href='#{root_url}category/#{category}'
                      | #{category}
                a href="#{root_url}collections/#{item.collection_id}"
                  |  from #{item.collection_title}
                a.twitter-share-button href="https://twitter.com/share" data-count="none" data-via=twitter_user data-text="Listen to #{@title} from #{item.collection_title}" Tweet
            .description
              p 
                span.date 
                  | #{item.date_created ? item.date_created.to_datetime.strftime('%m/%d/%Y') : ''}  
                | #{raw item.description}
            .clear
            .tplayer-bar
              .tplayer-bar-inner
              .jp-controls.pull-left
                button.jp-play.player-button id="jp-play-button-#{file_id}" data-collection='#{item.collection_title}' data-file='#{title} (#{file_id.to_s})'
                  i.fa.fa-play
                button.jp-pause.player-button id="jp-pause-button-#{file_id}"
                  i.fa.fa-pause
              .tplayer-stats.pull-right
                .jp-time-holder
                  .jp-current-time role="timer" aria-label="time" 
                  .sep
                    | /
                  .jp-duration role="timer" aria-label="duration" 
              .jp-progress
                .jp-seek-bar
                  .jp-play-bar
                / .scrubber
                  / canvas
            .clear
          .jp-no-solution
            span
              | Update Required
              | To play the media you will need to either update your browser to a recent version or update your 
              a href="http://get.adobe.com/flashplayer/" target="_blank"
                | Flash plugin
              | . 

app/views/embed_player/_tplayer_player_js.html.erb
<% file_id    ||= @file_id %>
<% audio_file ||= @audio_file || AudioFile.find(file_id.to_i) %>
<% title      ||= @title || audio_file.item.title %>
<% mp3        ||= @mp3   || audio_file.url(:mp3) %>
<% ogg        ||= @ogg   || audio_file.url(:ogg) %>
<% start      ||= @start || 0 %>
<% my_end     ||= @end   || false %>
<script type="text/javascript">
  $(document).ready(function(){
    $("#pua-tplayer-<%= file_id %>").jPlayer({
      ready: function (ev) {
        var playerUsed = ev.jPlayer.html.used ? 'html' : 'flash';
        //console.log('player used:', playerUsed);
        $(this).jPlayer("setMedia", {
          title: "<%= title %>",
          mp3: "<%= mp3 %>",
          oga: "<%= ogg %>",
        });
      },
      loadedmetadata: function() {
        var jplayer = this;
        jplayer.puaTplayer = new PUATPlayer({
          fileId: '<%= file_id %>',
          jplayer: jplayer,
          play: { start: parseInt(<%= start %>), end: <%= my_end %>, now: <%= @play_on_load ? 'true' : 'false' %> }
        });
      },
      ended: function() {
        var player = this;
        //console.log('player ended', player);
      },
      cssSelectorAncestor: '#jp_container-<%= file_id %>',
      smoothPlayBar: true,
      keyEnabled: true,
      remainingDuration: true,
      toggleDuration: true,
      swfPath: "<%= asset_path 'Jplayer.swf' %>",
      solution: "html, flash",
      supplied: "oga, mp3"
    });
  });
</script>
<%= javascript_include_tag "player" %>

app/views/embed_player/_tplayer_transcript.html.slim
- file_id    ||= @file_id
- audio_file ||= @audio_file || AudioFile.find(file_id.to_i)
- transcript ||= @transcript || @audio_file.best_transcript
- chunk_size ||= @chunk_size || 5
- short_url = ENV['SHORT_URL'] || root_url.gsub(/\/$/, '')
- perm_url  = root_url.gsub(/\/$/, '')
javascript:
  window.shortURL = '#{ENV['SHORT_URL'] || perm_url}';

.row-fluid
  .col-xs-12
    - if transcript
      form.ts-search
        .result-numbers
        input type="text" placeholder="Find in transcript"
        span.clear-find x
        button.search-submit type="submit" disabled="true"
          | find 
          i.fa.fa-search
        .last-result.inactive
          i.fa.fa-chevron-circle-up
        .next-result.inactive
          i.fa.fa-chevron-circle-down
      .tplayer.scrolling id="pua-tplayer-#{file_id}-transcript" data-file="#{file_id}" data-perm="#{audio_file.item_id.to_s(16)}"
          .hidden.loading-indicator
            .loading-text
              i.fa.fa-cog.fa-spin
              |  Seeking
          .body
            - tparts = transcript.has_speaker_ids ? transcript.chunked_by_speaker : transcript.chunked_by_time(chunk_size.to_i)
            - line_num = 0; tparts.each do |tpart|

              .row-fluid.timings-transcript
                .col-xs-12.col-md-2.timings
                  / = tpart[:speaker] + " "
                  = tpart[:ts]
                .col-xs-12.col-md-10.transcript
                  - tpart[:text].each_with_index do |ttext,idx|
                    .pua-tplayer-text id="pua-tplayer-text-#{file_id}-#{tpart[:offsets][idx].to_i}" data-idx="#{line_num += 1}" data-offset="#{tpart[:offsets][idx].to_i}"
                      .tools
                        span.ts
                          = tpart[:offsets][idx].to_i.to_s
                        i.share.fa.fa-twitter.fa-large data-toggle="modal" data-target="#share-modal-#{file_id}" data-offset="#{tpart[:offsets][idx].to_i.to_s}"
                      .text
                        = ttext
    - else
      |  Sadly, this audio has not yet been transcribed. Please try back later and/or let us know via 
      a href="mailto:edison@popuparchive.com" 
        | email
      | . 

app/views/embed_player/iframe.html.slim
doctype html
html
	iframe id='iframe' frameborder="0" style="overflow: hidden; height: 100%; width: 100%; position: absolute;" height="100%" width="100%" src="/tplayer/#{@file_id}"
		Sorry, your browser does not support iframe.
	.clear